apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"rosco\""},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"rosco","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-rosco"},"name":"spin-rosco","namespace":"spinnaker"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-rosco"}},"template":{"metadata":{"annotations":{},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"rosco","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-rosco"}},"spec":{"containers":[{"env":[{"name":"JAVA_OPTS","value":"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"},{"name":"SPRING_PROFILES_ACTIVE","value":"local"}],"image":"gcr.io/spinnaker-marketplace/rosco:0.11.0-20190322234525","lifecycle":{},"name":"rosco","ports":[{"containerPort":8087}],"readinessProbe":{"exec":{"command":["wget","--no-check-certificate","--spider","-q","http://localhost:8087/health"]}},"resources":{"limits":{},"requests":{}},"securityContext":null,"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-rosco-files-54428541"},{"mountPath":"/opt/rosco/config/packer","name":"spin-rosco-files-1077378739"},{"mountPath":"/opt/rosco/config/packer/scripts","name":"spin-rosco-files-2090299775"}]}],"imagePullSecrets":[],"terminationGracePeriodSeconds":60,"volumes":[{"name":"spin-rosco-files-2090299775","secret":{"secretName":"spin-rosco-files-2090299775"}},{"name":"spin-rosco-files-54428541","secret":{"secretName":"spin-rosco-files-54428541"}},{"name":"spin-rosco-files-1077378739","secret":{"secretName":"spin-rosco-files-1077378739"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"rosco"'
  creationTimestamp: null
  generation: 1
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: rosco
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.13.3
    cluster: spin-rosco
  name: spin-rosco
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker/deployments/spin-rosco
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-rosco
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: rosco
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.13.3
        cluster: spin-rosco
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
            -XX:MaxRAMFraction=2
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: docker.io/yangkai/rosco:latest
        imagePullPolicy: Never
        lifecycle: {}
        name: rosco
        ports:
        - containerPort: 8087
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8087/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-rosco-files-54428541
        - mountPath: /opt/rosco/config/packer
          name: spin-rosco-files-1077378739
        - mountPath: /opt/rosco/config/packer/scripts
          name: spin-rosco-files-2090299775
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-rosco-files-2090299775
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-2090299775
      - name: spin-rosco-files-54428541
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-54428541
      - name: spin-rosco-files-1077378739
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-1077378739
status: {}
