apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"front50\""},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"front50","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-front50"},"name":"spin-front50","namespace":"spinnaker"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-front50"}},"template":{"metadata":{"annotations":{},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"front50","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-front50"}},"spec":{"containers":[{"env":[{"name":"JAVA_OPTS","value":"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"}],"image":"gcr.io/spinnaker-marketplace/front50:0.16.2-20190406050308","lifecycle":{},"name":"front50","ports":[{"containerPort":8080}],"readinessProbe":{"exec":{"command":["wget","--no-check-certificate","--spider","-q","http://localhost:8080/health"]}},"resources":{"limits":{},"requests":{}},"securityContext":null,"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-front50-files-1710624551"},{"mountPath":"/root/.aws","name":"spin-front50-files-1009874309"},{"mountPath":"/home/spinnaker/.aws","name":"spin-front50-files-1009874309"}]}],"imagePullSecrets":[],"terminationGracePeriodSeconds":60,"volumes":[{"name":"spin-front50-files-1710624551","secret":{"secretName":"spin-front50-files-1710624551"}},{"name":"spin-front50-files-1009874309","secret":{"secretName":"spin-front50-files-1009874309"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"front50"'
  creationTimestamp: null
  generation: 1
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: front50
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.13.3
    cluster: spin-front50
  name: spin-front50
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker/deployments/spin-front50
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-front50
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: front50
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.13.3
        cluster: spin-front50
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
            -XX:MaxRAMFraction=2
        image: docker.io/yangkai/front50:latest
        imagePullPolicy: Never
        lifecycle: {}
        name: front50
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8080/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-front50-files-1710624551
        - mountPath: /root/.aws
          name: spin-front50-files-1009874309
        - mountPath: /home/spinnaker/.aws
          name: spin-front50-files-1009874309
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-front50-files-1710624551
        secret:
          defaultMode: 420
          secretName: spin-front50-files-1710624551
      - name: spin-front50-files-1009874309
        secret:
          defaultMode: 420
          secretName: spin-front50-files-1009874309
status: {}
