apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"clouddriver\""},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"clouddriver","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-clouddriver"},"name":"spin-clouddriver","namespace":"spinnaker"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-clouddriver"}},"template":{"metadata":{"annotations":{},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"clouddriver","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-clouddriver"}},"spec":{"containers":[{"env":[{"name":"JAVA_OPTS","value":"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"},{"name":"SPRING_PROFILES_ACTIVE","value":"local"}],"image":"gcr.io/spinnaker-marketplace/clouddriver:4.4.2-20190406050308","lifecycle":{},"name":"clouddriver","ports":[{"containerPort":7002}],"readinessProbe":{"exec":{"command":["wget","--no-check-certificate","--spider","-q","http://localhost:7002/health"]}},"resources":{"limits":{},"requests":{}},"securityContext":null,"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-clouddriver-files-277225993"},{"mountPath":"/home/spinnaker/.hal/default/staging/dependencies","name":"spin-clouddriver-files-1618949475"}]}],"imagePullSecrets":[],"terminationGracePeriodSeconds":720,"volumes":[{"name":"spin-clouddriver-files-277225993","secret":{"secretName":"spin-clouddriver-files-277225993"}},{"name":"spin-clouddriver-files-1618949475","secret":{"secretName":"spin-clouddriver-files-1618949475"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"clouddriver"'
  creationTimestamp: null
  generation: 1
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: clouddriver
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.13.3
    cluster: spin-clouddriver
  name: spin-clouddriver
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker/deployments/spin-clouddriver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-clouddriver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: clouddriver
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.13.3
        cluster: spin-clouddriver
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
            -XX:MaxRAMFraction=2
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: docker.io/yangkai/clouddriver:latest
        imagePullPolicy: Never
        lifecycle: {}
        name: clouddriver
        ports:
        - containerPort: 7002
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:7002/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-clouddriver-files-277225993
        - mountPath: /home/spinnaker/.hal/default/staging/dependencies
          name: spin-clouddriver-files-1618949475
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 720
      volumes:
      - name: spin-clouddriver-files-277225993
        secret:
          defaultMode: 420
          secretName: spin-clouddriver-files-277225993
      - name: spin-clouddriver-files-1618949475
        secret:
          defaultMode: 420
          secretName: spin-clouddriver-files-1618949475
status: {}
