apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"echo\""},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"echo","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-echo"},"name":"spin-echo","namespace":"spinnaker"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-echo"}},"template":{"metadata":{"annotations":{},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"echo","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.13.3","cluster":"spin-echo"}},"spec":{"containers":[{"env":[{"name":"JAVA_OPTS","value":"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"},{"name":"SPRING_PROFILES_ACTIVE","value":"local"}],"image":"gcr.io/spinnaker-marketplace/echo:2.4.1-20190403155503","lifecycle":{},"name":"echo","ports":[{"containerPort":8089}],"readinessProbe":{"exec":{"command":["wget","--no-check-certificate","--spider","-q","http://localhost:8089/health"]}},"resources":{"limits":{},"requests":{}},"securityContext":null,"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-echo-files-44608282"}]}],"imagePullSecrets":[],"terminationGracePeriodSeconds":60,"volumes":[{"name":"spin-echo-files-44608282","secret":{"secretName":"spin-echo-files-44608282"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"echo"'
  creationTimestamp: null
  generation: 1
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: echo
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.13.3
    cluster: spin-echo
  name: spin-echo
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker/deployments/spin-echo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: echo
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.13.3
        cluster: spin-echo
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
            -XX:MaxRAMFraction=2
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: docker.io/yangkai/echo:latest
        imagePullPolicy: Never
        lifecycle: {}
        name: echo
        ports:
        - containerPort: 8089
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8089/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-echo-files-44608282
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-echo-files-44608282
        secret:
          defaultMode: 420
          secretName: spin-echo-files-44608282
status: {}
