apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"spin","cluster":"spin-redis"},"name":"spin-redis","namespace":"spinnaker"},"spec":{"ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"spin","cluster":"spin-redis"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    app: spin
    cluster: spin-redis
  name: spin-redis
  selfLink: /api/v1/namespaces/spinnaker/services/spin-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: spin
    cluster: spin-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
