apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"spin","cluster":"spin-clouddriver"},"name":"spin-clouddriver","namespace":"spinnaker"},"spec":{"ports":[{"port":7002,"protocol":"TCP","targetPort":7002}],"selector":{"app":"spin","cluster":"spin-clouddriver"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    app: spin
    cluster: spin-clouddriver
  name: spin-clouddriver
  selfLink: /api/v1/namespaces/spinnaker/services/spin-clouddriver
spec:
  ports:
  - port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app: spin
    cluster: spin-clouddriver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
